<?php

namespace Container2EpKzrx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Biom8NPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Biom8NP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Biom8NP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\DashboardController::index' => ['privates', '.service_locator.I3XUlBy', 'get_ServiceLocator_I3XUlByService', true],
            'App\\Controller\\PostsController::VerPost' => ['privates', '.service_locator.I3XUlBy', 'get_ServiceLocator_I3XUlByService', true],
            'App\\Controller\\PostsController::index' => ['privates', '.service_locator.g0C.J1L', 'get_ServiceLocator_G0C_J1LService', true],
            'App\\Controller\\RegistroController::index' => ['privates', '.service_locator.dQsEc8u', 'get_ServiceLocator_DQsEc8uService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\DashboardController:index' => ['privates', '.service_locator.I3XUlBy', 'get_ServiceLocator_I3XUlByService', true],
            'App\\Controller\\PostsController:VerPost' => ['privates', '.service_locator.I3XUlBy', 'get_ServiceLocator_I3XUlByService', true],
            'App\\Controller\\PostsController:index' => ['privates', '.service_locator.g0C.J1L', 'get_ServiceLocator_G0C_J1LService', true],
            'App\\Controller\\RegistroController:index' => ['privates', '.service_locator.dQsEc8u', 'get_ServiceLocator_DQsEc8uService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\DashboardController::index' => '?',
            'App\\Controller\\PostsController::VerPost' => '?',
            'App\\Controller\\PostsController::index' => '?',
            'App\\Controller\\RegistroController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\DashboardController:index' => '?',
            'App\\Controller\\PostsController:VerPost' => '?',
            'App\\Controller\\PostsController:index' => '?',
            'App\\Controller\\RegistroController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
