<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTpnIb5S\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTpnIb5S/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTpnIb5S.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTpnIb5S\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTpnIb5S\App_KernelDevDebugContainer([
    'container.build_hash' => 'TpnIb5S',
    'container.build_id' => '4f24a086',
    'container.build_time' => 1686564575,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTpnIb5S');
