<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHxkJOnQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHxkJOnQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHxkJOnQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHxkJOnQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHxkJOnQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'HxkJOnQ',
    'container.build_id' => 'fc3ad0f4',
    'container.build_time' => 1686222094,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHxkJOnQ');
